;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-left-brace
	TeX-command-master
	TeX-insert-backslash
	TeX-insert-dollar
	beginning-of-buffer
	c-electric-brace
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	comment-line
	cua-copy-region
	cua-paste
	end-of-visual-line
	kill-region
	mouse-save-then-kill
	overwrite-mode
	py-electric-colon
	py-electric-comment
	py-electric-delete
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-visual-line
	cua--prefix-override-handler
	cua-cut-region
	mouse-set-region
	))
