(deftheme clues
  "Created 2018-06-28.")

(custom-theme-set-variables
 'clues
 '(fringe-mode 10))

(custom-theme-set-faces
 'clues
 '(cursor ((t (:background "orange"))))
 '(minibuffer-prompt ((t (:foreground "#1278A8" :background nil :weight bold))))
 '(escape-glyph ((t (:foreground "orange" :background nil))))
 '(highlight ((t (:foreground "orange" :background nil))))
 '(region ((t (:background "#342858"))))
 '(shadow ((t (:foreground "#777777" :background nil))))
 '(secondary-selection ((t (:background "#342858"))))
 '(trailing-whitespace ((t (:foreground "#FFFFFF" :background "#C74000"))))
 '(font-lock-builtin-face ((t (:foreground "#55B1E2" :background nil))))
 '(font-lock-comment-face ((t (:foreground "#90A0A0" :background nil :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#CFC5A9" :background nil))))
 '(font-lock-function-name-face ((t (:foreground "#BFC3A9" :background nil))))
 '(font-lock-keyword-face ((t (:foreground "#55C0D2" :background nil))))
 '(font-lock-negation-char-face ((t (:foreground "#C75311" :background nil))))
 '(font-lock-string-face ((t (:foreground "#94D4D9" :background nil))))
 '(font-lock-variable-name-face ((t (:foreground "#BDBA9F" :background nil))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#3499aa" :background nil :inherit (font-lock-comment-face)))))
 '(font-lock-preprocessor-face ((t (:foreground "#A16C26" :background nil :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#f66500" :background nil :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "red" :background nil :inherit (bold)))))
 '(font-lock-doc-face ((t (:foreground "#90A0A0" :background nil :inherit (font-lock-string-face)))))
 '(font-lock-warning-face ((t (:foreground "#008000" :background nil :inherit (error)))))
 '(font-lock-type-face ((t (:foreground "#55aadd" :background nil :inherit (default)))))
 '(link ((t (:foreground "#00b7f0" :background nil :underline t))))
 '(link-visited ((t (:foreground "#4488cc" :underline t :inherit (link)))))
 '(button ((t (:foreground "#FFFFFF" :background "#444444" :underline t :inherit (link)))))
 '(fringe ((t (:background "#1B0F1f"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(header-line ((t (:foreground "#EEEEEE" :background "#444444" :box nil :inherit (mode-line)))))
 '(mode-line-highlight ((t (:box nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-buffer-id ((t (:box nil :weight bold))))
 '(mode-line-inactive ((t (:foreground "#555555" :background "#111111" :box nil :weight light :inherit (mode-line)))))
 '(mode-line ((t (:foreground "#777777" :background "#111111" :box nil :inherit (variable-pitch)))))
 '(isearch ((t (:foreground "#99ccee" :background "#444444"))))
 '(isearch-fail ((t (:background "#ffaaaa"))))
 '(lazy-highlight ((t (:background "#77bbdd"))))
 '(match ((t (:background "#3388cc"))))
 '(tooltip ((t (:foreground "black" :background "LightYellow" :inherit (variable-pitch)))))
 '(default ((((class color) (min-colors 16777216)) (:foreground "#C0E9F6" :background "#110B14")) (((class color) (min-colors 88)) (:foreground "#fff" :background "#000")) (((class color) (min-colors 16)) (:foreground "#fff" :background "#000")) (((class color) (min-colors 8)) (:foreground "#fff" :background "#000")))))

(provide-theme 'clues)
